import type {Metadata} from 'next/types'

import {env} from '@/lib/env'
import {AppConfig} from '@/utils/AppConfig'

export const metadata: Metadata = {
  metadataBase: new URL(env.NEXT_PUBLIC_HOST || 'https://devs7ud.io'),
  title: 'DEVS7UD.IO',
  description: 'Generated by create next app',
  generator: AppConfig.name,
  applicationName: AppConfig.name,
  referrer: 'origin-when-cross-origin',
  keywords: AppConfig.keywords,
  authors: AppConfig.authors,
  creator: AppConfig.authors[0]?.name,
  icons: [
    {
      rel: 'apple-touch-icon',
      url: '/apple-touch-icon.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon-32x32.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon-16x16.png'
    },
    {
      rel: 'icon',
      url: '/favicon.ico'
    }
  ],
  manifest: '/manifest.json',
  formatDetection: {
    email: false,
    address: false,
    telephone: false
  },
  appleWebApp: {
    statusBarStyle: 'black-translucent'
  },
  robots: {
    index: true,
    follow: true
  },
  twitter: AppConfig.twitter
    ? {
        creator: `@${AppConfig.twitter}`
      }
    : undefined
}
