const protectedProfileConfig = {
  primaryTitle: "개인 정보",
  primarySubTitle: "개인 정보를 업데이트하세요.",
  secondaryTitle: "사용자 정보",
  secondarySubTitle: "사용자 정보 업데이트",
  formImageNote: "JPG, PNG 파일만 허용됩니다. 최대 5MB.",
  successMessageImageUpload: "이미지가 성공적으로 업로드되었습니다.",
  errorMessageImageUpload: "이미지를 업로드할 수 없습니다.",
  name: "전체 이름",
  firstName: "이름",
  firstNamePlaceholder: "이름",
  lastName: "성",
  lastNamePlaceholder: "성",
  userName: "사용자 이름",
  userNamePlaceholder: "사용자 이름",
  email: "이메일",
  emailPlaceholder: "이메일",
  website: "웹사이트",
  websitePlaceholder: "https://website.com",
  update: "프로필 업데이트",
  changeAvatar: "아바타 변경",
  uploadNote: "JPG, GIF 또는 PNG. 최대 5MB.",
  pleaseWait: "잠시만 기다려주세요...",
  successMessage: "프로필이 업데이트되었습니다.",
  errorMessage: "프로필을 업데이트하는 동안 오류가 발생했습니다.",
};

export default protectedProfileConfig;
