const protectedEditorConfig = {
  generalTitle: "일반 정보",
  generalDescription: "게시물의 일반 정보를 업데이트하세요",
  title: "에디터",
  slug: "슬러그",
  generateSlug: "슬러그 생성",
  description: "게시물을 업데이트하세요",
  formTitle: "제목",
  formSlug: "슬러그",
  categoryTitle: "카테고리",
  categoryDescription: "카테고리를 선택하세요",
  shortDescriptionTitle: "짧은 설명",
  shortDescriptionDescription: "게시물의 짧은 설명을 업데이트하세요",
  mainContentTitle: "주요 내용",
  mainContentDescription:
    "버블 메뉴가 있는 WYSIWYG 에디터, 이미지 드래그 앤 드롭 업로드 가능.",
  formImage: "이미지",
  formImageNote: "JPG, PNG 및 GIF 파일만 허용됩니다",
  formImageSize: "파일 크기는 6MB를 초과할 수 없습니다.",
  coverImageTitle: "커버 이미지",
  formCoverImageUploadFile: "파일 업로드",
  coverImageDescription: "커버 이미지를 하나 업로드할 수 있습니다.",
  galleryImageTitle: "갤러리 이미지",
  galleryImageDescription: "최대 ",
  submit: "업데이트",
  cancel: "취소",
  cofirm: "확인",
  placeHolderTitle: "블로그 게시물의 제목을 입력하세요",
  placeholderSlug: "블로그 게시물의 슬러그를 입력하세요",
  placeholderImage: "이미지 URL",
  deleteImage: "이미지 삭제",
  errorMessagesDeleteImage: "이미지 삭제 오류",
  errorMessageImageUpload: "이미지 업로드 오류",
  successMessagesDeleteImage: "이미지가 삭제되었습니다",
  successMessageImageUpload: "이미지가 업로드되었습니다",
  placeholderDescription:
    "블로그 게시물의 짧은 설명을 입력하세요",
  placeholderCategory: "카테고리를 선택하세요",
  placeholderContent: "블로그 게시물 내용을 입력하세요",
  defaultCategoryId: "4db30a13-2797-4c7d-a0ce-e0c127287a39", // 새소식
  successMessage: "게시물이 업데이트되었습니다",
  errorMessage: "게시물 업데이트 중 오류가 발생했습니다",
  chooseFile: "파일 업로드",
  thumbnail: "썸네일",
  coverPhoto: "커버 사진",
  uploadDescription: "PNG, JPG, GIF 최대 10MB",
  deleteImageQuestion: "이 이미지를 삭제하시겠습니까?",
  deleteImageDescription: "이 작업은 되돌릴 수 없습니다.",
};

export default protectedEditorConfig;