import '@fortawesome/fontawesome-svg-core/styles.css'
import '@/styles/global.css'

import {config} from '@fortawesome/fontawesome-svg-core'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {notFound} from 'next/navigation'
import {useMessages} from 'next-intl'

import {ThemeProvider} from '@/components/providers'
import {AppConfig} from '@/utils/AppConfig'

config.autoAddCss = false

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'DEVS7UD.IO',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'apple-touch-icon',
      url: '/apple-touch-icon.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon-32x32.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon-16x16.png'
    },
    {
      rel: 'icon',
      url: '/favicon.ico'
    }
  ],
  manifest: '/manifest.json'
}

export function generateStaticParams() {
  return AppConfig.locales.map((locale) => ({locale}))
}

type RootLayoutProps = Readonly<{
  children: React.ReactNode
  params: {locale: string}
}>

export default function RootLayout({children, params}: RootLayoutProps) {
  // Validate that the incoming `locale` parameter is valid
  if (!AppConfig.locales.includes(params.locale)) notFound()

  // Using internationalization in Client Components
  const messages = useMessages()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
          locale={params.locale}
          messages={messages}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

// export const runtime = 'edge';
